import { useEffect, useState } from 'react'
import './styles.css'
import './enhancements.css'
import './gaming.css'

const GTA = 'https://www.rockstargames.com/VI/_next/static/media/Official_Cover_Art_landscape.12.uu2irr.2_a.jpg?akim=1&imwidth=1920'
const LOGO = './assets/blvnd-logo.png'
const WHATSAPP = '94702744157'
const GAME_IMAGES = {
  'GTA V': 'https://cdn.cloudflare.steamstatic.com/steam/apps/3240220/header.jpg',
  'PRAGMATA': 'https://cdn.cloudflare.steamstatic.com/steam/apps/3357650/header.jpg',
  'SPIDER-MAN MILES MORALES': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1817190/header.jpg',
  'GHOST OF TSUSHIMA': 'https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg',
  'MORTAL KOMBAT 1': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1971870/header.jpg',
  'FC 26': 'https://cdn.cloudflare.steamstatic.com/steam/apps/3405690/header.jpg',
  'NFS PAYBACK': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1262580/header.jpg',
  'DIRT RALLY': 'https://cdn.cloudflare.steamstatic.com/steam/apps/690790/header.jpg'
}
const VENUE_IMAGES = {
  console: GAME_IMAGES['SPIDER-MAN MILES MORALES'],
  racing: GAME_IMAGES['NFS PAYBACK'],
  crew: GTA,
  snacks: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=1400&q=85'
}
const games = [
  ['GTA VI','FEATURED'], ['GTA V','CONSOLE'], ['PRAGMATA','CONSOLE'], ['SPIDER-MAN MILES MORALES','CONSOLE'], ['GHOST OF TSUSHIMA','CONSOLE'], ['MORTAL KOMBAT 1','2 PLAYERS MAX'], ['FC 26','COMING SOON'], ['NFS PAYBACK','RACING SIM'], ['DIRT RALLY','RACING SIM']
]
const standard = [['15 MIN',250,'Quick session'],['30 MIN',450,'Standard session'],['1 HOUR',750,'Best value']]
const gta = [['15 MIN',300,'GTA VI session'],['15 MIN + SNACK',550,'Session + snack or drink'],['STANDARD',750,'1 hour GTA VI session'],['GAMER COMBO',1100,'1 hour + snack or drink'],['CREW PACK',4200,'4 players + snacks + group photo'],['LAUNCH DAY VIP',1150,'Premium GTA VI experience']]
const money = n => `Rs. ${Number(n).toLocaleString('en-LK')}`

export default function BLVND(){
 const [loading,setLoading]=useState(true),[booking,setBooking]=useState(null),[menu,setMenu]=useState(false),[progress,setProgress]=useState(0)
 useEffect(()=>{let p=0;const i=setInterval(()=>{p=Math.min(100,p+4);setProgress(p);if(p===100){clearInterval(i);setTimeout(()=>setLoading(false),350)}},35);return()=>clearInterval(i)},[])
 const book=(game,pack)=>setBooking({game,pack})
 if(loading)return <Loader progress={progress}/>
 return <div className="app-shell gaming-app">
  <header className="nav"><a className="brand" href="#top"><img src={LOGO} alt="BLVND Arena"/><small>ARENA</small></a><nav className="desktop-nav"><a href="#gta">GTA VI</a><a href="#games">GAMES</a><a href="#packages">PACKAGES</a><a href="#arcade">ARENA</a></nav><button className="nav-book" onClick={()=>book('GTA VI',gta[2])}>BOOK NOW ↗</button><button className="menu-button" onClick={()=>setMenu(true)}>☰</button></header>
  <main>
   <section id="top" className="hero gaming-hero"><div className="hero-image" style={{backgroundImage:`url(${GTA})`}}/><div className="hero-scanlines"/><div className="hero-noise"/><div className="hero-content gaming-reveal"><div className="eyebrow"><span className="live-dot"/> GALLE, SRI LANKA · BOOKINGS OPEN</div><img className="hero-logo" src={LOGO} alt="BLVND Arena"/><h1>GTA <em>VI</em><br/><span>EXPERIENCE.</span></h1><p>THE NEXT SESSION STARTS AT BLVND.</p><div className="hero-actions"><button className="primary-btn pulse-btn" onClick={()=>book('GTA VI',gta[2])}>BOOK A SESSION ↗</button><a className="ghost-btn" href="#games">EXPLORE GAMES</a></div></div><div className="hero-corner">BLVND / 001<br/>GALLE · SRI LANKA</div><div className="scroll-cue">SCROLL ↓</div></section>
   <section id="gta" className="gta-section gaming-panel"><div className="section-grid"><div className="section-copy gaming-reveal"><span className="section-kicker">01 / FEATURED EXPERIENCE</span><h2>GTA <span>VI</span><br/>AT BLVND.</h2><p>GTA VI sessions in Galle. Pick your package, date and time, then send the request through WhatsApp.</p><div className="status"><span className="live-dot"/> SESSION BOOKINGS OPEN</div><button className="outline-btn" onClick={()=>book('GTA VI',gta[2])}>BOOK GTA VI ↗</button></div><div className="gta-art gaming-art" style={{backgroundImage:`url(${GTA})`}}><div className="art-caption">OFFICIAL GTA VI ARTWORK<br/><small>Rockstar Games</small></div></div></div></section>
   <section id="games" className="games-section"><div className="section-heading gaming-reveal"><span className="section-kicker">02 / THE LINEUP</span><h2>CHOOSE<br/><span>YOUR GAME.</span></h2><p>Console titles use standard BLVND rates. NFS Payback and DiRT Rally run on the racing simulator.</p></div><div className="game-grid">{games.map((g,i)=><button key={g[0]} className={`game-card gaming-card ${i===0?'game-featured':''} ${g[1]==='COMING SOON'?'coming-soon':''}`} onClick={()=>g[1]!=='COMING SOON'&&book(g[0],standard[2])}><div className={`game-photo ${i===0?'':'placeholder p'+i}`} style={{backgroundImage:`url(${i===0?GTA:GAME_IMAGES[g[0]]})`}}>{g[1]==='COMING SOON'&&<span className="coming-badge">COMING SOON</span>}</div><div className="game-overlay"/><div className="game-info"><span>{g[1]}</span><h3>{g[0]}</h3><div className="game-link">{g[1]==='COMING SOON'?'LOCKED':'BOOK ↗'}</div></div></button>)}</div></section>
   <section id="packages" className="packages-section"><div className="section-heading gaming-reveal"><span className="section-kicker">03 / SESSION RATES</span><h2>PLAY<br/><span>YOUR WAY.</span></h2></div><Rate title="ALL OTHER GAMES" packs={standard} onBook={p=>book('OTHER GAMES',p)} number="01"/><Rate title="GTA VI EXPERIENCE" packs={gta} onBook={p=>book('GTA VI',p)} number="02" gta/></section>
   <section className="crew-section"><div className="crew-bg" style={{backgroundImage:`url(${GTA})`}}/><div className="crew-overlay"/><div className="crew-content gaming-reveal"><span className="section-kicker">04 / FOR THE SQUAD</span><h2>BRING<br/><span>YOUR CREW.</span></h2><div className="crew-stats"><div><strong>04</strong><small>PLAYERS</small></div><div><strong>01</strong><small>HOUR</small></div><div><strong>04</strong><small>SNACKS</small></div><div><strong>01</strong><small>GROUP PHOTO</small></div></div><div className="crew-price">Rs. 4,200</div><button className="primary-btn" onClick={()=>book('GTA VI',gta[4])}>BOOK CREW PACK ↗</button></div></section>
   <section id="arcade" className="arcade-section"><div className="section-heading gaming-reveal"><span className="section-kicker">05 / THE ARENA</span><h2>MEET<br/><span>BLVND.</span></h2><p>Four experiences. One place to play, race, compete and hang with your crew.</p></div><div className="venue-grid"><Venue title="CONSOLE ZONE" text="PS5 gaming sessions" icon="▣" image={VENUE_IMAGES.console}/><Venue title="RACING SIM" text="NFS Payback + DiRT Rally" icon="◉" image={VENUE_IMAGES.racing}/><Venue title="CREW NIGHTS" text="Group sessions and events" icon="✦" image={VENUE_IMAGES.crew}/><Venue title="SNACKS" text="Fuel for the next round" icon="◆" image={VENUE_IMAGES.snacks}/></div><div className="location-card gaming-location" style={{backgroundImage:`linear-gradient(90deg,rgba(7,4,10,.96),rgba(7,4,10,.62)),url(${GTA})`}}><div><span className="section-kicker">FIND US</span><h3>BLVND ARENA</h3><p>Happugala, Galle, Sri Lanka</p></div><a href="https://www.google.com/maps/search/?api=1&query=Happugala%20Galle%20Sri%20Lanka" target="_blank" rel="noreferrer">GET DIRECTIONS ↗</a></div></section>
   <section className="booking-cta gaming-cta"><div className="cta-inner gaming-reveal"><span className="section-kicker">06 / READY?</span><h2>YOUR SESSION<br/><span>STARTS HERE.</span></h2><button className="primary-btn pulse-btn" onClick={()=>book('GTA VI',gta[2])}>BOOK NOW ↗</button></div></section>
  </main>
  <footer><div className="footer-brand"><img src={LOGO} alt="BLVND"/></div><div className="footer-bottom"><span>© {new Date().getFullYear()} BLVND ARENA</span><span>GALLE, SRI LANKA</span><span>WHATSAPP +94 70 274 4157</span></div></footer>
  {menu&&<div className="mobile-menu gaming-menu"><button className="close-menu" onClick={()=>setMenu(false)}>✕</button><img className="menu-logo" src={LOGO} alt="BLVND Arena"/><nav><a href="#gta" onClick={()=>setMenu(false)}>GTA VI</a><a href="#games" onClick={()=>setMenu(false)}>GAMES</a><a href="#packages" onClick={()=>setMenu(false)}>PACKAGES</a><a href="#arcade" onClick={()=>setMenu(false)}>ARENA</a></nav><button className="primary-btn" onClick={()=>{setMenu(false);book('GTA VI',gta[2])}}>BOOK NOW ↗</button></div>}
  {booking&&<Booking data={booking} close={()=>setBooking(null)}/>}</div>
}
function Loader({progress}){return <div className="blvnd-loader gaming-loader"><div className="loader-grid"/><div className="loader-glow"/><div className="loader-content"><img src={LOGO} className="loader-logo" alt="BLVND Arena"/><div className="loader-sub">ARENA · GALLE · SRI LANKA</div><div className="loader-line"><span style={{width:`${progress}%`}}/></div><div className="loader-status"><span>INITIALIZING ARENA</span><strong>{String(progress).padStart(2,'0')}%</strong></div></div><div className="loader-corner">GTA VI EXPERIENCE / 2026</div></div>}
function Rate({title,packs,onBook,number,gta}){return <div className={`rate-block reveal ${gta?'gta-rates':''}`}><div className="rate-title"><span>{number}</span><h3>{title}</h3><p>{gta?'Featured GTA VI session packages.':'PS5, racing, fighting, sports and more.'}</p></div><div className="rate-grid">{packs.map(p=><button className={`package-card ${p[0]==='CREW PACK'?'crew-package':''}`} key={p[0]} onClick={()=>onBook(p)}><div className="package-top"><span>{p[0]}</span></div><strong>{money(p[1])}</strong><p>{p[2]}</p><div className="package-book">BOOK ↗</div></button>)}</div></div>}
function Venue({title,text,icon,image}){return <div className="venue-tile reveal" style={{backgroundImage:`linear-gradient(180deg,rgba(7,4,10,.18),rgba(7,4,10,.94)),url(${image})`}}><div className="tile-icon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function Booking({data,close}){const[f,setF]=useState({name:'',phone:'',date:'',time:'',players:data.pack[0]==='CREW PACK'?4:1});const set=(k,v)=>setF(x=>({...x,[k]:v}));const submit=e=>{e.preventDefault();const t=encodeURIComponent(`BLVND ARENA BOOKING REQUEST\n\nGame: ${data.game}\nPackage: ${data.pack[0]}\nPrice: ${money(data.pack[1])}\nDate: ${f.date}\nTime: ${f.time}\nPlayers: ${f.players}\nName: ${f.name}\nWhatsApp: ${f.phone}\n\nPlease confirm my booking.`);window.open(`https://wa.me/${WHATSAPP}?text=${t}`,'_blank')};return <div className="modal-backdrop"><div className="booking-modal gaming-modal"><button className="modal-close" onClick={close}>✕</button><div className="booking-head"><span className="section-kicker">BOOK YOUR SESSION</span><h2>{data.game}<br/><span>{data.pack[0]}</span></h2><div className="booking-price">{money(data.pack[1])}</div></div><form onSubmit={submit}><label>NAME<input required value={f.name} onChange={e=>set('name',e.target.value)}/></label><label>WHATSAPP NUMBER<input required placeholder="07XXXXXXXX" value={f.phone} onChange={e=>set('phone',e.target.value)}/></label><div className="form-row"><label>DATE<input required type="date" value={f.date} onChange={e=>set('date',e.target.value)}/></label><label>TIME<input required type="time" value={f.time} onChange={e=>set('time',e.target.value)}/></label></div><label>PLAYERS<input type="number" min="1" max="4" value={f.players} onChange={e=>set('players',e.target.value)}/></label><button className="primary-btn submit-btn" type="submit">SEND TO WHATSAPP ↗</button></form></div></div>}
